// Code generated by "stringer -type=CheckoutMethod"; DO NOT EDIT.

package gitclone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidCheckoutMethod-0]
	_ = x[CheckoutNoneMethod-1]
	_ = x[CheckoutCommitMethod-2]
	_ = x[CheckoutTagMethod-3]
	_ = x[CheckoutBranchMethod-4]
	_ = x[CheckoutPRMergeBranchMethod-5]
	_ = x[CheckoutPRDiffFileMethod-6]
	_ = x[CheckoutPRManualMergeMethod-7]
	_ = x[CheckoutHeadBranchCommitMethod-8]
	_ = x[CheckoutForkCommitMethod-9]
}

const _CheckoutMethod_name = "InvalidCheckoutMethodCheckoutNoneMethodCheckoutCommitMethodCheckoutTagMethodCheckoutBranchMethodCheckoutPRMergeBranchMethodCheckoutPRDiffFileMethodCheckoutPRManualMergeMethodCheckoutHeadBranchCommitMethodCheckoutForkCommitMethod"

var _CheckoutMethod_index = [...]uint8{0, 21, 39, 59, 76, 96, 123, 147, 174, 204, 228}

func (i CheckoutMethod) String() string {
	if i < 0 || i >= CheckoutMethod(len(_CheckoutMethod_index)-1) {
		return "CheckoutMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CheckoutMethod_name[_CheckoutMethod_index[i]:_CheckoutMethod_index[i+1]]
}
